import Head from 'next/head'
import Image from 'next/image'
import About from '../components/Section/About'
import Card from '../components/Section/Card'
import Skills from '../components/Section/Skills'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen py-10 px-3 sm:px-5 bg-gray-200">
        <Card/>
        <About/>
        <Skills/>
      </div>


      
    </div>
  )
}
